VicLyfe/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VicLyfe.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Username")]
        public string UserName  { get { return "VicLyfe"; } }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember?")]
        public bool RememberMe { get; set; }
    }
}

VicLyfe/Controllers/HomeController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using VicLyfe.Model;

namespace VicLyfe.Controllers
{
    public class HomeController : Controller
    {
        private readonly double COOKIE_EXPIRES = 30;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PRPath()
        {
            ViewBag.Message = "Your PR Suggestions.";

            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [AllowAnonymous]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.UserName.Equals("admin") && model.Password.Equals("123456"))
            {
                string userData = new JavaScriptSerializer().Serialize(model);
                var ticket = new FormsAuthenticationTicket(1, model.UserName, DateTime.Now, DateTime.Now.AddDays(COOKIE_EXPIRES), false, userData, FormsAuthentication.FormsCookiePath);
                string encrypt = FormsAuthentication.Encrypt(ticket);
                var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encrypt);

                Response.Cookies.Remove(cookie.Name);
                Response.Cookies.Add(cookie);

                if (string.IsNullOrEmpty(returnUrl))
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                    return Redirect(returnUrl);
            }
            else
            {
                ModelState.AddModelError("", "Invalid Login");
                return View(model);
            }
        }
    }
}

VicLyfe/Controllers/VP1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VicLyfe.Controllers
{
    public class VP1Controller : Controller
    {

        public ActionResult ViewPage1()
        {
            ViewBag.Message = "View comparison of Metropolitan and Regional Areas";

            return View();
        }
    }
}

VicLyfe/Controllers/VP2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VicLyfe.Controllers
{
    public class VP2Controller : Controller
    {

        public ActionResult ViewPage2()
        {
            ViewBag.Message = "Comparison of different Regional Areas in Victoria in terms of Crime, Jobs and Rent";

            return View();
        }
    }
}

VicLyfe/Controllers/VP3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VicLyfe.Controllers
{
    public class VP3Controller : Controller
    {

        public ActionResult ViewPage3()
        {
            ViewBag.Message = "Select and view data about your City!";

            return View();
        }
    }
}

VicLyfe/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<style>
    body, h1, h2, h3, h4, h5 {
        font-family: "Raleway", sans-serif
    }
</style>
<html>
<body class="w3-light-grey">

    <div style="position: fixed">
    <font>&emsp;&emsp;&emsp;&emsp;&emsp;</font>
    <b style="TEXT-DECORATION: overline">*&emsp;&emsp;&emsp;&emsp;*</b>
    </div>

    <!-- w3-content defines a container for fixed size centered content,
    and is wrapped around the whole page content, except for the footer in this example -->
    <div class="w3-content" style="max-width:1400px">

        <!-- Header -->
        <header class="w3-container w3-center w3-padding-32">
            <h1><b>What is VicLyfe ?</b></h1>
            <p>Looking for a PR ? Do not Worry <span class="w3-tag">Regional Victoria - Move when your ready.</span></p>
        </header>

        <!-- Grid -->
        <div class="w3-row">

            <div class="responsive">
                <div class="w3-card-4 w3-margin w3-white">
                    <img src="~/Content/rendered-2.jpg" alt="Nature" style="width:100%; height:400px;">
                    <div class="w3-container">
                        <h3><b>Problems faced by recent graduates</b></h3>
                    </div>

                    <div class="w3-container">
                        <p>
                            Every year students come to Melbourne looking to build a professional career but when they
                            graduate they need a Permanent Residency to land a graduate job in most cases. Students with
                            no work experience are most affected as they are often short of 5 - 10 points. But now they
                            do not have to worry. Regional Victoria serves as a pathway for PR.

                        </p>
                        <div class="w3-row">
                            <div class="w3-col m8 s12">
                                <p>
                                    <button class="w3-button w3-padding-large w3-white w3-border">
                                        <ul>
                                            <li>@Html.ActionLink("Find out how ->", "PRPath", "Home")</li>
                                        </ul>
                                    </button>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>

                <div class="responsive">
                    <img src="~/Content/map-of-victoria-australia-s-guide-and-gippsland.jpg" alt="Norway" style="width:90%;height:450px;">
                    <div class="w3-container">
                        <h3><b>Not just PR. We help in finding a Regional City to live.</b></h3>
                        <h5>Compare the different regions and cities against Melbourne yourself</h5>
                    </div>

                    <div class="w3-container">
                        <p>
                            Considering the fact that moving from Melbourne to regional Victoria is not an easy decision,
                            we assist you with choosing the Region and City which is most suitable for you considering
                            your basic needs. We provide you a comparison of the Regional cities with Melbourne to give
                            you a basic idea of how good the quality of life there is.
                            Regional Victoria has 5 Regions: Loddon Mallee, Barwon South West, Gippsland, Grampians, Hume
                            Regional Victoria has 10 Cities: Geelong, Ballarat, Bendigo, Horsham, Latrobe, Mildura, Shepparton,
                            Wangaratta, Warrnambool, Wodonga.
                            Compare between these or compare them with Melbourne to find out which suits you.
                        </p>
                        <div class="w3-row">
                            <div class="w3-col m8 s12">
                                <p>
                                    <button class="w3-button w3-padding-large w3-white w3-border">
                                        <ul>
                                            <li>@Html.ActionLink("Choose a Region->", "ViewPage2", "VP2")</li>
                                            <li>@Html.ActionLink("Choose a City->", "ViewPage3", "VP3")</li>
                                        </ul>
                                    </button>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



            <!-- END GRID -->
        </div><br>

        <!-- END w3-content -->
    </div>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>

        .slider {
            width: 100%;
            height: 500px;
            display: flex;
            overflow-x: auto;
            align-content: center;
        }

        .slide {
            width: 500px;
            flex-shrink: 0;
            height: 600px;
            align-content: center;
        }
    </style>

    <h2> Regional Victoria Cities </h2>
    <div class="slider">

        <div class="slide">
            <div class="numbertext">1 / 10</div>
            <img src="~/Content/City-1.png" style="width:100%">
        </div>

        <div class="slide">
            <div class="numbertext">2 / 10</div>
            <img src="~/Content/City2.png" style="width:100%">
        </div>

        <div class="slide">
            <div class="numbertext">3 / 10</div>
            <img src="~/Content/City3.png" style="width:100%">
        </div>

        <div class="slide">
            <div class="numbertext">4 / 10</div>
            <img src="~/Content/City4.png" style="width:100%">
        </div>

        <div class="slide">
            <div class="numbertext">5 / 10</div>
            <img src="~/Content/City5.png" style="width:100%">
        </div>

        <div class="slide">
            <div class="numbertext">6 / 10</div>
            <img src="~/Content/City6.png" style="width:100%">
        </div>

        <div class="slide">
            <div class="numbertext">7 / 10</div>
            <img src="~/Content/City7.png" style="width:100%">
        </div>

        <div class="slide">
            <div class="numbertext">8 / 10</div>
            <img src="~/Content/City8.png" style="width:100%">
        </div>

        <div class="slide">
            <div class="numbertext">9 / 10</div>
            <img src="~/Content/City9.png" style="width:100%">
        </div>

        <div class="slide">
            <div class="numbertext">10 / 10</div>
            <img src="~/Content/City10.png" style="width:100%">
        </div>
    </div>
    <br />
    <!-- Footer -->
    <footer class="w3-container w3-black w3-padding-32 w3-margin-top">
        <p style="text-align:center;"><a href="https://regionalliving.vic.gov.au/" target="_blank">Visit Regional Victoria Government Site</a></p>
    </footer>

</body>
</html>

VicLyfe/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<div style="position: fixed">
    <b>&ensp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</b>
    <b style="TEXT-DECORATION: overline; color:red;">*&emsp;&emsp;&emsp;*</b>
</div>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">

    <html>
    <body>

        <!-- Top menu -->
        <div class="img-responsive">
            <h3 style="text-align:center; color:grey;"> <b> Still Confused ?</b> </h3>
            <h4 style="text-align:center; color:grey;"> See the resources you can consider for help</h4>
        </div>

        <!-- !PAGE CONTENT! -->
        <div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">

            <!-- First Photo Grid-->
            <div class="w3-row-padding w3-padding-16 w3-center" id="food">
                <div class="w3-quarter">
                    <img src="~/Content/Jobs-link.jpg" alt="Jobs" style="width:100%">
                    <h3>Make a move only when your ready.</h3>
                    <p>Find out more about jobs in Regional Victoria</p>
                    <p><a href="https://regionalliving.vic.gov.au/why-regional-victoria/jobs" target="_blank">Click Here</a></p>
                </div>
                <div class="w3-quarter">
                    <img src="~/Content/Hospital.png" alt="Hospital" style="width:100%">
                    <h3>Have health conditions ?</h3>
                    <p>Make sure you know about Regional Health Services and Benefits.</p>
                    <p><a href="https://regionalliving.vic.gov.au/why-regional-victoria/health" target="_blank">Click Here</a></p>
                </div>
                <div class="w3-quarter">
                    <img src="~/Content/cost-of-living.jpg" alt="Cost" style="width:100%">
                    <h3>Can I afford my living in Regiona Victoria?</h3>
                    <p>Fine out here.</p>
                    <p><a href="https://emsaus.com/blog/cost-living-regional-areas/" target="_blank">Click Here</a></p>

                </div>
                <div class="w3-quarter">
                    <img src="~/Content/PR.jpg" alt="PR" style="width:100%">
                    <h3>Still not sure of the PR benefits?</h3>
                    <p>Look for some of the best migration agents here.</p>
                    <p><a href="https://liveinmelbourne.vic.gov.au/connect/employer-visas-and-visa-nomination/regional-sponsored-migration-scheme" target="_blank">Click Here</a></p>

                </div>
            </div>

            <hr id="about">

            <!-- About Section -->
            <div class="w3-container w3-padding-32 w3-center">
                <h3>Make your move when you when your ready.</h3><br>
                <img src="~/Content/20151118_regionalvictoria.png" alt="Victoria" class="w3-image" style="display:block;margin:auto" width="800" height="533">
                <div class="w3-padding-32">
                    <h4><b>A beautiful awaits for you here.</b></h4>
                    <h6><i>Life filled with happiness and passion</i></h6>
                    <p>
                        Victorian government offers a range of services and benefits for people moving to Regional
                        Victoria. Perform a detailed analysis by yourself though our application as well as outisde
                        sources and move confidently. Wishing you good Luck !
                    </p>
                </div>
            </div>
            <hr>
            <footer class="w3-center w3-black w3-padding-64">
                <ul>
                    <li background-color="grey">@Html.ActionLink("Go Back to Home Page", "Index", "Home")</li>
                </ul>
                <div class="w3-xlarge w3-section">
                    <i class="fa fa-facebook-official w3-hover-opacity"></i>
                    <i class="fa fa-instagram w3-hover-opacity"></i>
                    <i class="fa fa-snapchat w3-hover-opacity"></i>
                    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
                    <i class="fa fa-twitter w3-hover-opacity"></i>
                    <i class="fa fa-linkedin w3-hover-opacity"></i>
                </div>
            </footer>

            <!-- End page content -->
        </div>

        <script>
            // Script to open and close sidebar
            function w3_open() {
                document.getElementById("mySidebar").style.display = "block";
            }

            function w3_close() {
                document.getElementById("mySidebar").style.display = "none";
            }
        </script>

    </body>
</html>

VicLyfe/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}



<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    h1, h2, h3, h4, h5, h6 {
        font-family: "Oswald"
    }

    body {
        font-family: "Open Sans"
    }
</style>
<html>
<body class="w3-light-grey">


    <!-- w3-content defines a container for fixed size centered content,
    and is wrapped around the whole page content, except for the footer in this example -->
    <div class="w3-content" style="max-width:1600px">

        <!-- Header -->
        <header class="w3-container w3-center w3-padding-48 w3-white">
            <h1 class="w3-xxxlarge"><b>VicLyfe - A new beginning</b></h1>
            <h6>Regional Victoria <span class="w3-tag">The place to be</span></h6>
        </header>

        <!-- Image header -->
        <header class="w3-display-container w3-wide" id="home">
            <img class="w3-image" src="~/Content/DSC_6931.jpg" alt="Fashion Blog" width="1600" height="1060">
            <div class="w3-display-left w3-padding-large">
                <h1 class="w3-text-black">VicLyfe, For Graduates</h1>
                <h1 class="w3-jumbo w3-text-black w3-hide-small"><b>Moving to Regional Victoria</b></h1>
                <h6>
                    <button class="w3-button w3-white w3-padding-large w3-large w3-opacity w3-hover-opacity-off">
                        <ul>
                            <li background-color="grey">@Html.ActionLink("Know More", "About", "Home")</li>
                        </ul>
                    </button>
                </h6>
            </div>
        </header>
        <div class="w3-container" style="padding:32px 16px" id="about">
            <p class="responsive" style="text-align:center; margin-top:10px;margin-bottom:20px;">
                Today’s world is smaller than it has ever been. Places that once seemed too far away to ever imagine travelling
                there now feel within reach, offering new and exciting opportunities to begin life afresh.
                And so it is for the many thousands of people who come from lands afar to make Australia their new home.
                Regional Victoria is hugely active in attracting and supporting migrants in setting up their new lives. From help
                with the many visa options available, to the provision of useful resources such as those linked below, regional cities
                and shires offer invaluable assistance to make the process of moving
                into their region from overseas as smooth and successful as possible.
            </p>

            <div class="w3-container" style="padding:64px 16px" id="about">
                <h3 class="w3-center">What Regional Victoria Offers for you ?</h3>
                <p class="w3-center w3-large">A Never ending satisfaction just a few minutes away from you.</p>
                <div class="w3-row-padding w3-center" style="margin-top:50px">
                    <div class="w3-quarter">
                        <i class="fa fa-desktop w3-margin-bottom w3-jumbo w3-center"></i>
                        <p class="w3-large">Jobs</p>
                        <p>
                            One of the biggest concerns of anyone planning to move is that of employment. You are not alone here ! We have
                            plenty of resources to offer.
                        </p>
                    </div>
                    <div class="w3-quarter">
                        <i class="fa fa-heart w3-margin-bottom w3-jumbo"></i>
                        <p class="w3-large">Cost and Quality of Living</p>
                        <p>
                            Enjor superior quality of life with affordable cost of housing and other facilities. Do not pay more when you
                            can enjoy the same benefits at a much reasonable price.
                        </p>
                    </div>
                    <div class="w3-quarter">
                        <i class="fa fa-diamond w3-margin-bottom w3-jumbo"></i>
                        <p class="w3-large">Hospitals</p>
                        <p>
                            Equal number of Health care centers are in Regional Victoria to. You do not have to worry about not having access
                            to emergency health services. Explore Hospitals around you in a click !
                        </p>
                    </div>
                    <div class="w3-quarter">
                        <i class="fa fa-cog w3-margin-bottom w3-jumbo"></i>
                        <p class="w3-large">Safety and Security</p>
                        <p>
                            A wonderful place to live and build your career with very low crime rate and stress free life. Do not have to worry
                            about any emergency incidents. Victorian Police Services are always with you.
                        </p>
                    </div>
                </div>
            </div>
            <!-- Promo Section - "We know design" -->
            <div class="w3-container w3-light-grey" style="padding:32px 16px">
                <div class="w3-row-padding">
                    <div class="w3-col m6">
                        <h3>We know why Regional Victoria is Better than Melbourne.</h3>
                        <p>Do not make false assumptions. Compare and find out yourself.</p>
                        <p><i class="fa fa-th"> </i> View Our Data Visuals</p>
                        <ul>
                            <li>@Html.ActionLink("Click Here", "ViewPage1", "VP1")</li>
                        </ul>
                    </div>
                    <div class="w3-col m6">
                        <img class="w3-image w3-round-large" src="~/Content/1-1024x978.png" alt="Graphs" width="700" height="394">
                    </div>
                </div>
            </div>


            <!-- Inspiration -->
            <div class="w3-white w3-margin">
                <div class="w3-container w3-padding w3-black">
                    <h4>Check out some of the Major Places</h4>
                </div>
                <div class="w3-row-padding w3-white">
                    <div class="w3-col s6">
                        <p><img src="~/Content/Ballarat.jpg" alt="Jeans" style="width:100%"></p>
                        <p><img src="~/Content/Bendigo.jpg" alt="Jeans" style="width:100%"></p>
                    </div>
                    <div class="w3-col s6">
                        <p><img src="~/Content/Geelong.jpg" alt="Men in Hats" style="width:100%" class="w3-grayscale"></p>
                        <p><img src="~/Content/BAWBAW.jpg" alt="Jeans" style="width:100%"></p>
                    </div>
                </div>
            </div>
            <hr>
        </div>

        <!-- Footer -->
        <footer class="w3-center w3-black w3-padding-64">
            <ul>
                <li background-color="grey">@Html.ActionLink("Go Back to the Top", "Index", "Home")</li>
            </ul>
            <div class="w3-xlarge w3-section">
                <i class="fa fa-facebook-official w3-hover-opacity"></i>
                <i class="fa fa-instagram w3-hover-opacity"></i>
                <i class="fa fa-snapchat w3-hover-opacity"></i>
                <i class="fa fa-pinterest-p w3-hover-opacity"></i>
                <i class="fa fa-twitter w3-hover-opacity"></i>
                <i class="fa fa-linkedin w3-hover-opacity"></i>
            </div>
        </footer>



        <script>
            // Toggle between hiding and showing blog replies/comments
            document.getElementById("myBtn").click();
            function myFunction(id) {
                var x = document.getElementById(id);
                if (x.className.indexOf("w3-show") == -1) {
                    x.className += " w3-show";
                } else {
                    x.className = x.className.replace(" w3-show", "");
                }
            }

            function likeFunction(x) {
                x.style.fontWeight = "bold";
                x.innerHTML = "✓ Liked";
            }
        </script>

</body>
</html>

VicLyfe/Views/Home/Login.cshtml
@model VicLyfe.Model.LoginViewModel

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container">
        <h1>Login</h1>
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Home",
            new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post,
            new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "red-text" })
                <div class="form-group" >
                    @Html.LabelFor(m => m.UserName, new { @class = "col m2 control-label" })
                    <div class="col m10">
                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "red-text" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col m2 control-label" })
                    <div class="col m10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "red-text" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col m10 offset-m10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col m10 offset-m10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
            }
        </section>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>